server:
  port: 8080
spring:
 
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rentalcar?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  